### PR TITLE
Case importer distinguished smallvar and SV DB info files

### LINKED ISSUE #13: Database info files are not distinguished between Smallvars and SVs
**Describe the bug**
DB info files during the import do not distinguish between smallvars and SVs import. This causes problems downstream in VarFish as it maintains the info for both.

**To Reproduce**
See ticket in VarFish Server repos (link below).

**Expected behavior**
Distinguish between smallvars and SVs database info during file guessing, or at least before triggering the import in VarFish Server.

**Additional context**
Related issue in VarFish Server repository: bihealth/varfish-server#497

### LINKED ISSUE #497: Fix database version import behaviour when importing only one variant type
**Describe the bug**
When only importing SV information then only the sv database information should be overwritten not the small variant database information. The current combination of `varfish-cli` and `varfish-server`, the import information for svs overwrites the one of small variants.

**To Reproduce**
1. Import small variants file with one annotator database version
2. Import structural variants file with another annotator database version
3. See that the small variant database information is overwritten

**Expected behavior**
Only the database information file for the imported variant type should be overwritten.

**Additional context**
- Backport to `anthenea` branch.
- Potential duplicate: #498

### PR DESCRIPTION
**Pull request by stolpeo**
Closes: #13
Related-Issue: #13

Closes: bihealth/varfish-server#497
Related-Issue: bihealth/varfish-server#497

### CODE REVIEW

**Review by holtgrewe — CHANGES_REQUESTED** [review]
Tests break?

**Comment by stolpeo** [comment]
@holtgrewe yes, but somehow it seems to be related to SimpleNamespaces. They also break in main branch

**Comment by stolpeo** [comment]
Never used pytest before, will take some time to look into how this is supposed to work

**Comment by stolpeo** [comment]
The tests send a string as date, so this fails.

https://github.com/bihealth/varfish-cli/blob/8c17d5df19b2f3c1da1487750324138e85ef0fe7/varfish_cli/api/models.py#L575

However, sending a datetime object by removing `.isoformat()` makes the mocker fail.

https://github.com/bihealth/varfish-cli/blob/8c17d5df19b2f3c1da1487750324138e85ef0fe7/tests/test_run_case_list.py#L19

**Comment by stolpeo** [comment]
@holtgrewe OK issue is fixed. Also, I ran black, so there are some more (formatting) changes.

**Comment by stolpeo** [comment]
@holtgrewe OK had to fix flake8 concerns as well

**Comment by stolpeo** [comment]
Bumped black to solve dependency issue

**Review by holtgrewe — APPROVED** [review]
LGTM

**Pull request merged**
